name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -v -o ./bin/gohooked

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        files: ./bin/gohooked
        asset-name: gohooked_${{ github.run_number }}
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Changes in this release.
          
    - name: Upload Release Asset
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/gohooked
        asset_name: gohooked
